services:

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile-Node-Hurl
    user: node
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    network_mode: bridge
    links:
      - postgres
    ports:
      - "3000:3000"
      - "5173:5173"

  postgres:
    image: postgres:17.6
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: elo

volumes:
  postgres-data:
